/**
 * @typedef {Object} Movie
 * @property {boolean} adult - Indicates if the movie is for adult audiences.
 * @property {string} backdrop_path - Path to the backdrop image.
 * @property {null|Object} belongs_to_collection - Information about the collection the movie belongs to.
 * @property {number} budget - The movie's budget in dollars.
 * @property {Array<Genre>} genres - List of genres associated with the movie.
 * @property {string} homepage - Official homepage URL of the movie.
 * @property {number} id - Unique identifier for the movie.
 * @property {string} imdb_id - IMDb identifier for the movie.
 * @property {Array<string>} origin_country - List of countries where the movie originated.
 * @property {string} original_language - Original language of the movie.
 * @property {string} original_title - Original title of the movie.
 * @property {string} overview - Synopsis of the movie.
 * @property {number} popularity - Popularity score of the movie.
 * @property {string} poster_path - Path to the poster image.
 * @property {Array<ProductionCompany>} production_companies - List of production companies involved.
 * @property {Array<ProductionCountry>} production_countries - List of production countries.
 * @property {string} release_date - Release date in YYYY-MM-DD format.
 * @property {number} revenue - Total revenue generated by the movie.
 * @property {number} runtime - Duration of the movie in minutes.
 * @property {Array<SpokenLanguage>} spoken_languages - List of spoken languages in the movie.
 * @property {string} status - Current status of the movie (e.g., "Released").
 * @property {string} tagline - Tagline for the movie.
 * @property {string} title - Official title of the movie.
 * @property {boolean} video - Indicates if there's an associated video.
 * @property {number} vote_average - Average user rating.
 * @property {number} vote_count - Number of votes received.
 */

/**
 * @typedef {Object} Genre
 * @property {number} id - Unique identifier for the genre.
 * @property {string} name - Name of the genre.
 */

/**
 * @typedef {Object} ProductionCompany
 * @property {number} id - Unique identifier for the company.
 * @property {string} logo_path - Path to the company's logo.
 * @property {string} name - Name of the company.
 * @property {string} origin_country - Country where the company is based.
 */

/**
 * @typedef {Object} ProductionCountry
 * @property {string} iso_3166_1 - ISO 3166-1 country code.
 * @property {string} name - Full country name.
 */

/**
 * @typedef {Object} SpokenLanguage
 * @property {string} english_name - English name of the language.
 * @property {string} iso_639_1 - ISO 639-1 language code.
 * @property {string} name - Native name of the language.
 */
